# Generated by Django 4.0.4 on 2022-05-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_products2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products2',
        ),
    ]
