# Generated by Django 4.0.4 on 2022-05-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_products2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
    ]
